# Generated by Django 4.2.4 on 2023-08-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_city_alter_customuser_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_judge',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_player',
        ),
    ]
