# Generated by Django 4.2.5 on 2023-09-30 22:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='judge',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge', to='manager.competitor'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manager.matchtype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 0, 9, 43, 211969)),
        ),
    ]
