# Generated by Django 4.2.5 on 2023-09-30 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_match_judge_alter_match_match_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player_1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 0, 17, 41, 217463)),
        ),
    ]
