# Generated by Django 4.2.4 on 2023-08-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_match_options_tournament_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='competitor',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='is_judge',
            field=models.BooleanField(default=False, verbose_name='judge'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='is_player',
            field=models.BooleanField(default=False, verbose_name='player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='address',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='city',
            field=models.CharField(blank=True, default='Lubartów', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='country',
            field=models.CharField(default='Poland', max_length=128),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='place',
            field=models.CharField(max_length=128),
        ),
    ]
