# Generated by Django 5.0.2 on 2024-03-23 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_match_player_1_score_match_player_2_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 18, 50, 52, 814972)),
        ),
    ]
