# Generated by Django 4.2.4 on 2023-08-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_remove_competitor_is_approved_competitor_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='city',
            field=models.CharField(default='Lubartów', max_length=128),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(default=None),
        ),
    ]
