# Generated by Django 5.0.3 on 2024-03-25 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_match_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 18, 27, 51, 469854)),
        ),
    ]
