# Generated by Django 4.2.4 on 2023-08-26 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_tournament_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 19, 47, 52, 336768)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
