# Generated by Django 4.2.4 on 2023-08-26 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_match_start_date_alter_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 20, 9, 9, 503208)),
        ),
    ]
